spring:
  application:
    name: nexflow-api
  messages:
    basename: messages
  jackson:
    mapper:
      accept-case-insensitive-enums: true
server:
  servlet:
    context-path: /nexflow/api
  port: 8080

springdoc:
  swagger-ui:
    path: /doc
  override-with-generic-response: false
  default-produces-media-type: application/json