spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  jwt:
    private-key: private-key-developer-jwt-123456789
    issuer: nexflow-dev
server:
  servlet:
    context-path: /nexflow/api
springdoc:
  swagger-ui:
    path: /doc
  override-with-generic-response: false
  default-produces-media-type: application/json
swagger:
  server:
    path: http://localhost:8080/nexflow/api/
user:
  initial:
    name: User
    surnames: Dev
    email: user@gmail.com
    password: devuser1234