spring:
  sql:
    init:
      mode: always
  application:
    name: nexflow-api
  messages:
    basename: messages
  jpa:
    hibernate:
      ddl-auto: create-drop
  jackson:
    mapper:
      accept-case-insensitive-enums: true
  security:
    user:
      name: user
      password: 1234
  jwt:
    private-key: key-dev-profile